### ISSUE TITLE
Update aws-sdk package to v3

### ISSUE THREAD

**Issue by punkle** [segmentio/segment-backstage-plugins#8]
AWS have notified that they will put aws-sdk into maintenance mode in September 2024 and stop supporting it completely in September 2025.

It would be great if we could update this plugin to use version 3 of the AWS libraries.

https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/

**Comment by alecjacobs5401** [comment]
Thanks for reporting! This has been a lingering doom for a bit and definitely something we should get on top of.

**Comment by alecjacobs5401** [comment]
This should actually be resolved now as of https://github.com/segmentio/segment-backstage-plugins/pull/10! Sorry for not following up sooner here
